# Generated by Django 4.1.5 on 2023-01-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0005_content_like_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'managed': True, 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
