# Generated by Django 4.1.5 on 2023-01-13 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empire', '0006_alter_content_options_alter_content_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
